spring:
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: ${DEV_DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DEV_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}
      embedded: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${DEV_URL}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${DEV_URL}/login/oauth2/code/{registrationId}"

custom:
  oauth2:
    redirect-url: ${DEV_OAUTH2_REDIRECT_URI}
