spring:
  datasource:
    url: ${TEST_DATASOURCE_URL}
    username: ${TEST_DATASOURCE_USERNAME}
    password: ${TEST_DATASOURCE_PASSWORD}
    driver-class-name: ${TEST_DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${TEST_JPA_HIBERNATE_DDL_AUTO}
  data:
    redis:
      host: ${TEST_REDIS_HOST}
      port: ${TEST_REDIS_PORT}
      password: ${TEST_REDIS_PASSWORD}
      embedded: true
