spring:
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: ${DEV_DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DEV_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}
      embedded: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${DEV_OAUTH2_KAKAO_REDIRECT_URI}
          naver:
            redirect-uri: ${DEV_OAUTH2_NAVER_REDIRECT_URI}

custom:
  cors:
    allowed-origins: ${DEV_CORS_ALLOWED_ORIGINS}
  oauth2:
    redirect-url: ${DEV_OAUTH2_SUCCESS_REDIRECT_URL}
    failure-url: ${DEV_OAUTH2_FAILURE_REDIRECT_URL}
  frontend:
    url: ${DEV_FRONTEND_URL}
