name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main, develop, 'release/**' ]
  pull_request:
    branches: [ main, develop, 'release/**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test-ci
    services:
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: ""
      qdrant:
        image: qdrant/qdrant:v1.3.1
        ports:
          - 6333:6333
          - 6334:6334
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21 (Gradle cache on)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x backend/gradlew

      - name: Wait for services
        run: |
          timeout 10s bash -c 'until printf "" 2>/dev/null >>/dev/tcp/localhost/6379; do sleep 1; done'
          timeout 40s bash -c 'until curl -sSf http://localhost:6333/collections >/dev/null; do sleep 1; done'

      - name: Create test .env
        working-directory: backend
        run: |
          set -euo pipefail
          install -d -m 700 .
          echo "${{ secrets.DEV_ENV_BASE64 }}" | base64 -d > .env
          chmod 600 .env
          test -s .env || { echo ".env is empty"; exit 1; }

      - name: Run unit tests
        working-directory: backend
        run: ./gradlew --no-daemon clean test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: backend/build/reports/tests
          retention-days: 7

  build-artifacts:
    name: Build backend JAR (main/release only)
    needs: tests
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Create build .env file
        working-directory: backend
        run: |
          set -euo pipefail
          install -d -m 700 .
          echo "${{ secrets.PROD_ENV_BASE64 }}" | base64 -d > .env
          chmod 600 .env
          test -s .env || { echo ".env is empty"; exit 1; }

      - name: Build bootJar (skip tests; already validated)
        working-directory: backend
        run: ./gradlew --no-daemon clean bootJar -x test

      - name: Prepare dist
        working-directory: backend
        run: |
          mkdir -p dist
          cp $(ls build/libs/*.jar | grep -v plain | head -n 1) dist/app.jar

      - name: Upload backend jar
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/dist/app.jar
          if-no-files-found: error

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true